source 'https://rubygems.org'

gem 'volt', '0.9.0'
gem 'volt-bootstrap', '~> 0.0.10'
gem 'volt-bootstrap_jumbotron_theme', '~> 0.1.0'
gem 'volt-user_templates', '~> 0.1.3'
gem 'volt-wysiwyg', path: '../'

group :development, :test do
  gem 'rspec', '~> 3.2.0'
  gem 'opal-rspec', '~> 0.4.2'
  gem 'capybara', '~> 2.4.2'
  gem 'selenium-webdriver', '~> 2.43.0'
  gem 'chromedriver2-helper', '~> 0.0.8'
  gem 'poltergeist', '~> 1.5.0'
end

platform :mri do
  gem 'thin', '~> 1.6.0'
  gem 'bson_ext', '~> 1.9.0'
end
