source 'https://rubygems.org'

gem 'volt', '0.8.26'
gem 'volt-bootstrap'
gem 'volt-bootstrap_jumbotron_theme'
gem 'volt-user_templates'
gem 'volt-wysiwyg', path: '../'

group :development, :test do
  gem 'rspec'
  gem 'opal-rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'chromedriver2-helper'
  gem 'poltergeist'
end

platform :mri do
  gem 'thin'
  gem 'bson_ext'
end
